export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';
export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
export const MISSING_JWT_SECRET = 'MISSING_JWT_SECRET';
export const INVALID_TOKEN_PAYLOAD = 'INVALID_TOKEN_PAYLOAD';
