export const USER_VALIDATION_FAILED = 'USER_VALIDATION_FAILED';
export const FAILED_TO_CREATE_TRANSACTION = 'FAILED_TO_CREATE_TRANSACTION';
export const FAILED_TO_CALCULATE_BALANCE = 'FAILED_TO_CALCULATE_BALANCE';
export const INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS';
export const ERROR_FETCHING_TRANSACTIONS = 'ERROR_FETCHING_TRANSACTIONS';
export const FAILED_TO_CONNECT_USER_SERVICE = 'FAILED_TO_CONNECT_USER_SERVICE';
export const INVALID_TOKEN_PAYLOAD = 'INVALID_TOKEN_PAYLOAD';
export const MISSING_JWT_SECRET = 'MISSING_JWT_SECRET';
