export const USER_VALIDATION_FAILED = 'USER_VALIDATION_FAILED';
export const FAILED_TO_CREATE_TRANSACTION = 'FAILED_TO_CREATE_TRANSACTION';
export const FAILED_TO_CALCULATE_BALANCE = 'FAILED_TO_CALCULATE_BALANCE';
